mysql:
 host: localhost
 port: 3306
 database: db
 username: root
 password: pass
settings:
 bind-commands: true
 top: 10
 max: 100000 # Максимальное значение
 start: 15 # Сколько денег выдавать игроку при первом входе
messages:
 take-success: '§6Экономика §8| §fДеньги §aуспешно §rсняты'
 give-success: '§6Экономика §8| §fДеньги §aуспешно §rначислены'
 no-balance: '§6Экономика §8| §fИгрока с данным §6никнеймом §rнет в базе.'
 int-error: '§6Экономика §8| §fСумма денег должна быть числом.'
 no-perms: '§6Экономика §8| §fУ вас §cнедостаточно§f прав.'
 no-accounts: '§6Экономика §8| §fВ БД нет ни одного человека.'
 no-nick: '§6Экономика §8| §fНеобходимо указать никнейм.'
 no-value: '§6Экономика §8| §fНеобходимо указать сумму.'
 balance: '§6Экономика §8| §fУ вас §a%count §rмонет.'
 other-balance: '§6Экономика §8| §fУ §6%player §fсейчас: §a%count §fмонет.'
 pay: '§6Экономика §8| §fИгроку §a%player §rпередано §a%count §rмонет.'
 add: '§6Экономика §8| §fИгроку §a%player §rдобавлено §as%count §rмонет.'
 set: '§6Экономика §8| §fБаланс игрока §a%player §rустановлен на §a%count §rмонет.'
 top_1: '   §f=-=-=-=-= §6ТОП %num §f=-=-=-=-='
 top_2: ' §6%player §r- §e%count §rмонет'
 help:
  - '§6Экономика §8| §fСписок команд:'
  - '§6* §fПроверить свой баланс - §e/money'
  - '§6* §fПередать монетки - §e/pay ник кол-во'
  - '§6* §fПоказать топ самых богатых - §e/bal top'
 max-balance: '§6Экономика §8| §fПосле проведения данной операции, будет достигнут максимальный лимит баланса. §cОтмена.'
 no-money: '§6Экономика §8| §fУ вас §cнедостаточно §fсредств для проведения операции.'
 no-account: '§6Экономика §8| §fАккаунт данного игрока не найден.'
